### ISSUE TITLE
0.19: use of undeclared identifier 'POSIX_MADV_NORMAL'

### ISSUE THREAD

**Issue by kwek20** [rust-rocksdb/rust-rocksdb#697]
Hi!

I am cross compiling rocksdb from WSL to android, which worked in 0.18.  (`cargo build --target aarch64-linux-android --release`)
However when i compile on 0.19 i get the following error:
```
warning: rocksdb/env/io_posix.cc:1001:41: error: use of undeclared identifier 'POSIX_MADV_NORMAL'
warning:       Madvise(mmapped_region_, length_, POSIX_MADV_NORMAL);
warning:                                         ^
warning: rocksdb/env/io_posix.cc:1004:41: error: use of undeclared identifier 'POSIX_MADV_RANDOM'
warning:       Madvise(mmapped_region_, length_, POSIX_MADV_RANDOM);
warning:                                         ^
warning: rocksdb/env/io_posix.cc:1007:41: error: use of undeclared identifier 'POSIX_MADV_SEQUENTIAL'
warning:       Madvise(mmapped_region_, length_, POSIX_MADV_SEQUENTIAL);
warning:                                         ^
warning: rocksdb/env/io_posix.cc:1010:41: error: use of undeclared identifier 'POSIX_MADV_WILLNEED'
warning:       Madvise(mmapped_region_, length_, POSIX_MADV_WILLNEED);
warning:                                         ^
warning: rocksdb/env/io_posix.cc:1013:41: error: use of undeclared identifier 'POSIX_MADV_DONTNEED'
warning:       Madvise(mmapped_region_, length_, POSIX_MADV_DONTNEED);
warning:                                         ^
warning: 5 errors generated.
```
Full error: https://pastebin.com/GHRrK3t3

I have traced the error to this commit: https://github.com/rust-rocksdb/rust-rocksdb/commit/17471a6da79918445ac4d8cef1dc37e9db86d384. (Bump rocksdb to 7.4.3)

I import the crate in the following way: 
Broken: `rocksdb = { version = "0.19.0", default-features = false, features = [ "lz4" ], optional = true }`
Working: `rocksdb = { git = "https://github.com/rust-rocksdb/rust-rocksdb", rev = "947e4b63034fff2151f52c399a5d85925ea80911", default-features = false, features = ["lz4"], optional = true }`

Any ideas how to fix this?
Thanks!

**Comment by samuel-rufi** [comment]
Hi, just wanted to note I have run into the same problem when cross compiling for Android on macOS.

**Comment by amadeu2** [comment]
Hello, I have the same issue on coss compiling for iOS and Android.
